name: Manual build, run & execute tests

on:
  workflow_dispatch:
  
jobs:

  run:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        
    steps:    
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'   
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Package proj & run containers
        run: |
          mvn -DskipTests=true package
          docker-compose up
            
        #- name: Extract allure reports #Настроить извличение отчетов
        #  run: |
        #    docker cp <container_id>:/app/allure-results ./allure-results
        
        #- name: Publish Allure report
        #  uses: allure-framework/allure-github-actions@v2.11.0
        #  with:
        #    path: ./allure-results
            
      - name: Disable docker
        run: docker-compose stop

