name: Manual build, run & execute tests

on:
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest

        
    steps:
    
      - name: Load share-it project #забираем проект из ветки докера
        uses: actions/checkout@v2
        with:
          repository: 'SugarFoxy/java-shareit'
          path: 'java-shareit'
          ref: 'refs/heads/add-docker'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'   
      - name: Build project
        run: |
          cd java-shareit
          ls
          ./mvnw clean package
          
#      - name: Run docker-compose #запускаем сборку проекта
#        uses: docker/compose-action@v2
#        with:
#          file: 'java-shareit/docker-compose.yml'          
